### ISSUE TITLE
Font Awesome Take Down Request

### ISSUE THREAD

**Issue by alexpoiry** [StoicDreams/MyFiCDN#1]
Hello,

I am the head of security for Font Awesome. This repository contains a complete collection of all our Font Awesome Pro assets (https://github.com/StoicDreams/MyFiCDN/tree/main/cdn/fa). These cannot be made available for free via a public repository, as is indicated by the license file which you have in the same file path. I would like to politely request that you remove these items from your repo and all branches.

I assume you didn't intend to violate our license and so would like to work with you and give you the time and opportunity to correct these issues before filing a DMCA request with GitHub. Please respond to this issue and provide a point of contact so that we can work to remedy this issue.

**Comment by erikgassler** [comment]
> Hello,
> 
> I am the head of security for Font Awesome. This repository contains a complete collection of all our Font Awesome Pro assets (https://github.com/StoicDreams/MyFiCDN/tree/main/cdn/fa). These cannot be made available for free via a public repository, as is indicated by the license file which you have in the same file path. I would like to politely request that you remove these items from your repo and all branches.
> 
> I assume you didn't intend to violate our license and so would like to work with you and give you the time and opportunity to correct these issues before filing a DMCA request with GitHub. Please respond to this issue and provide a point of contact so that we can work to remedy this issue.

Are you actually with Font Awesome? You don't seem like you actually are. You're posting this directly on GitHub from what looks like a fake GitHub account that uses a gmail address. My company's contact email [support@stoicdreams.com](mailto:support@stoicdreams.com) is clearly discoverable at [https://github.com/StoicDreams](https://github.com/StoicDreams) - why are you asking for contact info when the information is there.

The license file you refer to in the path specified says nothing about the restriction you are stating. Nor does the license that license links to at [https://fontawesome.com/license](https://fontawesome.com/license) from what I am understanding in the language.

The [Font Awesome Docs](https://docs.fontawesome.com/web/setup/host-yourself/svg-js) themselves include instructions that are explicitly clear that self-hosting FA assets are one of the recommended ways of distributing icons.

Furthermore, I have had communication with the Font Awesome team directly about this very subject - putting the font assets in a CDN for all of my websites to share - and it was made clear from that communication that the responsibility of people adhering to the license is on those companies and developers using Font Awesome, even if they are using it from my CDN, not on me as someone who has a legal Pro license to use Font Awesome Pro and is distributing the assets for use in my projects.

If you are legitimately from the Font Awesome team and this is a legitimate issue, then please send appropriate communication to [support@stoicdreams](mailto:support@stoicdreams). I expect any legit communication to be coming from an email from the `fontawesome.com` domain, as has been the case with all other legit communications I have had with Font Awesome.

**Comment by alexpoiry** [comment]
Fair enough sir, I have sent an email per your request from my fontawesome.com account and CC'd our head of support and CTO.

I appreciate your security minded approach by not accepting my personal email as proof of my employment with Font Awesome and have updated my primary email to that end.

I believe the salient portion of the license is here: https://fontawesome.com/license#what-creators-may-not-do.  But we can continue the conversation via support.
